#ifndef _DEFS__H
#define _DEFS__H

#define WINDOW_TITLE "Score Accumulating Incremental"
#define SCREEN_WIDTH 1400
#define SCREEN_HEIGHT 800
#define MAINBOARD_WIDTH SCREEN_WIDTH * 0.5
#define MAINBOARD_HEIGHT SCREEN_HEIGHT * 0.72
#define SIDEBOARD_WIDTH SCREEN_WIDTH*0.3
#define SIDEBOARD_HEIGHT SCREEN_HEIGHT
#define TOTAL_DATA 10

#define MAX_KEYBOARD_KEYS 350

#define FRAME_PER_SECOND 60

#define BG_COLOR_R 96
#define BG_COLOR_G 128
#define BG_COLOR_B 255
#define BG_COLOR_A 255

#endif
