name: Build and Release SAI

on: [ push, pull_request ]
permissions: write-all

env:
  VERSION: V0.0.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Install dependencies
        run: sudo apt update && sudo apt-get install cmake g++ libsdl2-dev libsdl2-image-dev mingw-w64 libsdl2-ttf-dev zip p7zip-full

      - name: Build
        run: |
          mkdir build
          cd build
          x86_64-w64-mingw32-windres -i ../project.rc -o project.o
          cmake .. -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ -DCMAKE_RC_COMPILER=x86_64-w64-mingw32-windres
          make

      - name: Copy assets and SDL DLLs
        run: |
          cp -r assets build/
          cp /usr/lib/x86_64-linux-gnu/libSDL2.dll build/
          cp /usr/lib/x86_64-linux-gnu/libSDL2_image.dll build/
          cp /usr/lib/x86_64-linux-gnu/libSDL2_ttf.dll build/

      - name: Zip the build
        run: |
          cd build
          7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on Score_Accumulating_Incremental.7z .

      - name: Generate release notes
        run: |
          echo "Release notes for ${{ github.ref }}:" > release-notes.txt
          git log --pretty=format:"- %s" >> release-notes.txt

      - name: Create tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag ${{ env.VERSION }}

      - name: Release
        uses: softprops/action-gh-release@v2.0.2
        with:
          files: build/Score_Accumulating_Incremental.7z
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          body_path: release-notes.txt